name: Info
on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write

    runs-on: macos-latest

    steps:
      - name: Print objects
        run: echo ${{ github.ref_name }}
             echo ${{ fromJson(github) }}
             echo ${{ fromJson(github.event) }}
             echo ${{ fromJson(github.event.payload) }}
